config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :incomes do 
    resources :categories
    resources :costs
  end
  resources :costs do
    resources :categories
    resources :incomes
  end
  resources :categories do
    resources :costs
    resources :incomes
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :user
	has_many :costs, dependent: :destroy
	has_many :incomes, dependent: :destroy
	validates :name, :presence => true
	validates_uniqueness_of :name
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  validates :category_id, :presence => true
  validates :name, :presence => true
  validates :amount, :presence => true, :numericality => { :greater_than => 0 }
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  validates :category_id, :presence => true
  validates :name, :presence => true
  validates :amount, :presence => true, :numericality => { :greater_than => 0 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :category
  has_many :costs
  has_many :incomes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # store last url - this is needed for post-login redirect to whatever the user last visited. return unless request.get?
  before_action :authenticate_user!

  def after_sign_out_path_for(resource)
  	request.referrer
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #def recent_categories
   # Category.select("category.*, COUNT(cost.id) AS count").where("category.created_at >= 1.week.ago.utc").joins("category LEFT JOIN costs cost on category.id=cost.category_id").order("count, created_at DESC")
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :user_id)
    end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @category = Category.find(params[:category_id])
    @cost = @category.costs.create(cost_params)
    #@cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @category, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
        format.js
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:category_id, :name, :amount, :user_id)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @category = Category.find(params[:category_id])
    @income = @category.incomes.create(income_params)
    #@income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @category, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
        format.js
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:category_id, :name, :amount, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.select(:name, options_for_select([["General Income","General Income"], ["Salary","Salary"], ["Investment","Investment"], ["Gift","Gift"], ["Business","Business"], ["General Cost","General Cost"], ["Bills","Bills"], ["Clothes","Clothes"], ["Food", "Food"], ["Entertainment","Entertainment"], ["Personal","Personal"], ["Transportation","Transportation"], ["Education","Education"], ["Home","Home"], ["Medical","Medical"], ["Insurance","Insurance"] ])) %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<center>
<br>
<h3>Editing Category</h3>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>
</center>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div id="wrapper">

<div id="leftside">
<br>
<font color="blue">
<h3>Navigation</h3></font><br>
<ul>
<li><%= link_to 'Categories', categories_path %></li>
<li><%= link_to 'All Incomes', incomes_path %></li>
<li><%= link_to 'All Costs', costs_path %></li>
</ul>
</div>

<div id="content">
<br>
<font color="blue">
<h3>Listing Categories</h3></font><br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <% if user_signed_in? %>
        <% if current_user.id == category.user_id %>
        <td><%= category.name %></td>
        <td><td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% total_income = 0 %>
<% current_user.incomes.each do |income| %>
  <% if user_signed_in? %>
    <% if current_user.id == income.user_id %>
      <% total_income = total_income + income.amount %>
    <% end %>
  <% end %>
<% end %>

<% total_cost = 0 %>
<% date = 0 %>
<% current_user.costs.each do |cost| %>
  <% if user_signed_in? %>
    <% if current_user.id == cost.user_id %>
      <% total_cost = total_cost + cost.amount %>
      <% date= cost.created_at.strftime("%d").to_i %>
    <% end %>
  <% end %>
<% end %>

<% alert_cost = 0 %>
<% current_user.costs.each do |cost| %>
  <% if user_signed_in? %>
    <% if current_user.id == cost.user_id %>
      <% date1 = cost.created_at.strftime("%d").to_i %>
      <% if date1 == date || date1 == date-1 || date1 == date-2 || date1== date-3 || date1== date-4 || date1== date-5 || date1== date-6 %>
        <% alert_cost = alert_cost + cost.amount %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%= link_to 'New Category', new_category_path %>

</div>

<div id="rightsidebar">
<div id="rightsidebartop">
<br>
<font color="blue">
<h3>Account Status</h3></font><br>
Total Incomes = $<%= total_income %>
<br>Total Costs = $<%= total_cost %>
<br>Total Savings = $<%= total_income-total_cost %>
</div>
<div id="rightsidebartop">
<br>
<font color="blue">
<h3>Alerts</h3></font><br>
<br>
<% alert = (alert_cost*100)/(total_income-total_cost) %>
<% if alert > 24 %>
<font color="red">
  Hello User!
  <p>You used more than 25% of your available balance in one week.</p>
  Available Balance = $<%= total_income-total_cost %>
  <br>Used in 1 Week = $<%= alert_cost %>
  <br>Thank you
</font>
<% else %>
  No Alerts
<% end %>
</div>
</div>

app/views/categories/new.html.erb
<style type="text/css"><!--
#wrap {
   width: 400px;
   margin:0 auto;
}
#left_col {
   float:left;
   width: 200px;
}
#right_col {
   float:right;
   width: 200px;
}
--></style>

<center>
<br>
<h3>New Category</h3>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>
<br>
</center>

<div id="wrap">
<div id="left_col"><br>
<strong>Income Category Names</strong>
<ul>
<li>General Income</li>
<li>Salary</li>
<li>Investment</li>
<li>Gift</li>
<li>Business</li>
</ul>
</div>
<div id="right_col"><br>
<strong>Cost Category Names</strong>
<ul>
<li>General Expense</li>
<li>Bills</li>
<li>Clothes</li>
<li>Food</li>
<li>Entertainment</li>
<li>Personal</li>
<li>Transportation</li>
<li>Education</li>
<li>Home</li>
<li>Medical</li>
<li>Insurance</li>
</ul>
</div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<br>
<h3>Category</h3>
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<br>
<% clicked = @category.name %>
<% if clicked == "General Income" || clicked == "Salary" || clicked == "Investment" || clicked == "Gift" || clicked == "Business"%>
<br>
<h3>Incomes</h3>
<br>
<h5>Existing Incomes in <%= @category.name %>:</h5>
<div id="incomes">
	<%= render :partial => @category.incomes.reverse %>
</div>
<br>
<h5>To Add Incomes in <%= @category.name %>:</h5>
<%= form_for([@category, Income.new], remote: true) do |f| %>
	<p><%= f.label :name, "New Income Name" %><br />
		<%= f.text_field :name %>
	</p>
	<p><%= f.label :amount, "New Income Amount" %><br />
		<%= f.number_field :amount %>
		<%= f.hidden_field :user_id, value: current_user.id %>
	</p>
	<br>
	<p><%= f.submit "Add Income" %></p>
<% end %>

<% else %>

<h3>Costs</h3>
<br>
<h5>Existing Costs in <%= @category.name %>:</h5>
<div id="costs">
	<%= render :partial => @category.costs.reverse %>
</div>
<br>
<h5>To Add Costs in <%= @category.name %>:</h5>
<%= form_for([@category, Cost.new], remote: true) do |f| %>
	<p><%= f.label :name, "New Cost Name" %><br />
		<%= f.text_field :name %>
	</p>
	<p><%= f.label :amount, "New Cost Amount" %><br />
		<%= f.number_field :amount %>
		<%= f.hidden_field :user_id, value: current_user.id %>
	</p>
	<br>
	<p><%= f.submit "Add Cost" %></p>
<% end %>

<% end %>
<br>
<%= link_to 'Back', categories_path %>
</center>

app/views/costs/_cost.html.erb
<%= div_for cost do %>
 <p>
 	<%= h(cost.name) %>:
	<%= h(cost.amount) %>
 </p>
<% end %>

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/costs/create.js.erb
var new_cost = $("<%= escape_javascript(render(:partial => @cost))%>").hide();
$('#costs').prepend(new_cost);
$('#cost_<%= @cost.id %>').fadeIn('slow');
$('#new_cost')[0].reset();

app/views/costs/edit.html.erb
<center>
<br><br>
<h3>Editing Cost</h3>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>
</center>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<div id="wrapper">

<div id="leftside">
<br>
<font color="blue">
<h3>Navigation</h3></font>
<br>
<ul>
<li><%= link_to 'Categories', categories_path %></li>
<li><%= link_to 'All Incomes', incomes_path %></li>
<li><%= link_to 'All Costs', costs_path %></li>
</ul>
</div>

<div id="content">
<br>
<font color="blue">
<h3>Listing Costs</h3></font>
<br>
<% total_cost = 0 %>
<% date = 0 %>
<table>
  <thead>
    <tr>
      <th>Category</th>
      <th></th>
      <th>Name</th>
      <th></th>
      <th>Amount</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <% if user_signed_in? %>
        <% if current_user.id == cost.user_id %>
        <td><%= cost.category.name %></td>
        <td></td>
        <td><%= cost.name %></td>
        <td></td>
        <td><%= cost.amount %></td>
        <td></td>
        <td><%= link_to 'Show', cost %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% total_cost = total_cost + cost.amount %>
        <% date= cost.created_at.strftime("%d").to_i %>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
Total Costs = <%= total_cost %>
<br>

<% total_income = 0 %>
<% current_user.incomes.each do |income| %>
  <% if user_signed_in? %>
    <% if current_user.id == income.user_id %>
      <% total_income = total_income + income.amount %>
    <% end %>
  <% end %>
<% end %>

<% alert_cost = 0 %>
<% current_user.costs.each do |cost| %>
  <% if user_signed_in? %>
    <% if current_user.id == cost.user_id %>
      <% date1 = cost.created_at.strftime("%d").to_i %>
      <% if date1 == date || date1 == date-1 || date1 == date-2 || date1== date-3 || date1== date-4 || date1== date-5 || date1== date-6 %>
        <% alert_cost = alert_cost + cost.amount %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<!-- <%= link_to 'New Cost', new_cost_path %> -->
</div>

<div id="rightsidebar">
<div id="rightsidebartop">
<br>
<font color="blue">
<h3>Account Status</h3></font>
<br>
Total Incomes = $<%= total_income %>
<br>Total Costs = $<%= total_cost %>
<br>Total Savings = $<%= total_income-total_cost %>
</div>
<div id="rightsidebartop">
<br>
<font color="blue">
<h3>Alerts</h3></font>
<br>
<% alert = (alert_cost*100)/(total_income-total_cost) %>
<% if alert > 24 %>
<font color="red">
  Hello User!
  <p>You used more than 25% of your available balance in one week.</p>
  Available Balance = $<%= total_income-total_cost %>
  <br>Used in 1 Week = $<%= alert_cost %>
  <br>Thank you
</font>
<% else %>
  No Alerts
<% end %>
</div>
</div>

app/views/costs/new.html.erb
<h1>New Cost</h1>

<%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<center>
<br><br>
<p>
  <strong>Category:</strong>
  <%= @cost.category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cost.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @cost.amount %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>
</center>

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/_income.html.erb
<%= div_for income do %>
 <p>
	<%= h(income.name) %>:
	<%= h(income.amount) %>
 </p>
<% end %>

app/views/incomes/create.js.erb
var new_income = $("<%= escape_javascript(render(:partial => @income))%>").hide();
$('#incomes').prepend(new_income);
$('#income_<%= @income.id %>').fadeIn('slow');
$('#new_income')[0].reset();

app/views/incomes/edit.html.erb
<center>
<br>
<h3>Editing Income</h3>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>
</center>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<div id="wrapper">

<div id="leftside">
<br>
<font color="blue">
<h3>Navigation</h3></font><br>
<ul>
<li><%= link_to 'Categories', categories_path %></li>
<li><%= link_to 'All Incomes', incomes_path %></li>
<li><%= link_to 'All Costs', costs_path %></li>
</ul>
</div>

<div id="content">
<br>
<font color="blue">
<h3>Listing Incomes</h3></font><br>
<% total_income = 0 %>
<table>
  <thead>
    <tr>
      <th>Category</th>
      <th></th>
      <th>Name</th>
      <th></th>
      <th>Amount</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <% if user_signed_in? %>
        <% if current_user.id == income.user_id %>
        <td><%= income.category.name %></td>
        <td></td>
        <td><%= income.name %></td>
        <td></td>
        <td><%= income.amount %></td>
        <td></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% total_income = total_income + income.amount %>
        <% end %>
        <% end %>
      </tr>
      <% end %>
  </tbody>
</table>
<br>
Total Incomes = <%= total_income %>

<br>

<% total_cost = 0 %>
<% date = 0 %>
<% current_user.costs.each do |cost| %>
  <% if user_signed_in? %>
    <% if current_user.id == cost.user_id %>
      <% total_cost = total_cost + cost.amount %>
      <% date= cost.created_at.strftime("%d").to_i %>
    <% end %>
  <% end %>
<% end %>

<% alert_cost = 0 %>
<% current_user.costs.each do |cost| %>
  <% if user_signed_in? %>
    <% if current_user.id == cost.user_id %>
      <% date1 = cost.created_at.strftime("%d").to_i %>
      <% if date1 == date || date1 == date-1 || date1 == date-2 || date1== date-3 || date1== date-4 || date1== date-5 || date1== date-6 %>
        <% alert_cost = alert_cost + cost.amount %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<!-- <%= link_to 'New Income', new_income_path %> -->
</div>

<div id="rightsidebar">
<div id="rightsidebartop">
<br>
<font color="blue">
<h3>Account Status</h3></font><br>
Total Incomes = $<%= total_income %>
<br>Total Costs = $<%= total_cost %>
<br>Total Savings = $<%= total_income-total_cost %>
</div>
<div id="rightsidebartop">
<br>
<font color="blue">
<h3>Alerts</h3></font><br>
<br>
<% alert = (alert_cost*100)/(total_income-total_cost) %>
<% if alert > 24 %>
<font color="red">
  Hello User!
  <p>You used more than 25% of your available balance in one week.</p>
  Available Balance = $<%= total_income-total_cost %>
  <br>Used in 1 Week = $<%= alert_cost %>
  <br>Thank you
</font>
<% else %>
  No Alerts
<% end %>
</div>
</div>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<center>
<br><br>
<p>
  <strong>Category:</strong>
  <%= @income.category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @income.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>
<center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>e-Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<style type="text/css"><!--
article, section, aside, hgroup, nav, header, figure, figcaption { 
    display: block;
}

*{
    margin: 0px;
    padding: 0px;
}
body {
    margin-left: 0px;
    margin-top: 0px;
}
img {
    border: none;
}
#wrapper {
    width: 990px;
    height: 600px;
    margin-right: auto;
    margin-left: auto;
}
header {
    background-color:black;
    height: 50px;
}
#leftside {
    width: 290px;
    height: 470px;
    float: left;
}

#content {
    width: 500px;
    height: 470px; 
    float: left;
}
#rightsidebar {
    width: 200px;
    height: 470px; 
    float: left;
}
#rightsidebartop {
    width: 245px;
    height: 235px; 
    float: left; 
}
#rightsidebarbottom {
    width: 245px;
    height: 235px; 
    float: left; 
}
#footer{
    background-color:black;
    position:fixed;
    height: 60px;
    bottom:0px;
    left:0px;
    right:0px;
    margin-bottom:0px;
}
--></style>

<body>

<header><center><br>
  <font color="red">
  <h1>~@~ Welcome to e-Wallet ~@~</h1>
  <h6>An app to store your money flow</h6>
</font>
<br></center></header>
<br>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

<div id="footer">
  <center>
    <%= image_tag("footer.jpg", :alt => "eWallet", :size => "40") %>
  </center>
    <center><font color="red">
    Developed by Deepak Velagaleti
  </font></center>
</div>
</body>
</html>